name: CI

# Trigger
on: [push]

# jobs to do
jobs:
  # we have a build job
  build:
    # base image
    runs-on: ubuntu-latest

    # steps to perform in build job
    steps:
    # Checks out / Brings the repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Sets up a specified version of Python and adds it to PATH
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # Builds the Docker image
    - name: Build Docker Image
      run: docker build -t flix-task .

    # Runs the Docker container and executes the tests
    # The container runs in detached mode and sleeps for 10 seconds to allow the service to start
    # Afterward, it runs pytest to execute the tests, and then the logs are outputted
    # for review if needed
    - name: Run Tests inside Docker
      run: |
        docker run --name flix-task-container -d flix-task:latest /bin/sh -c "sleep 10 && pytest /code/tests"
        docker logs flix-task-container
