name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build Docker Image
      run: docker build -t flix-task .

    - name: Run Tests inside Docker
      run: |
        docker run --name flix-task-container -d flix-task:latest /bin/sh -c "sleep 10 && pytest /code/tests"
        docker logs flix-task-container
